version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:5001"
    container_name: api
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db
volumes:
  db_data:
    
    